# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2eef01d8a8ae70aee834c706ea45081ed781754bd559453a190174dc602d2fa19b6a4cb87b3a5064a6578b8a962e9de2cc51cfe6ba33c0b9fe67a6addb534582

test:
  secret_key_base: ae3b1a303f2d16d035688a272a4aa171622c8eb4ccf9a4c3c6a821f309741a5d3ef36f54214c59617c0076e827dc06e3bec5a70e2e275d51d0462a9e9fe3b8e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
